### ISSUE TITLE
how to set the markless.customStyle ?

### ISSUE THREAD

**Issue by ariefcfa** [Sean10/markless#39]
sorry noob question. i tried using relative path to a .css file in my `workspace` but i didn't see any change

chatGPT gave a complicated answer and i'm not sure about that, by editing the `setting.json` file. something like:

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": "markup.list",
            "settings": {
...
```

please help

**Comment by Sean10** [comment]
Can you upload the content of your css file?

**Comment by ariefcfa** [comment]
thanks @Sean10 here is the screenshot

![Image](https://github.com/user-attachments/assets/5b9ed132-a174-4860-85b5-1f40c4113058)

**Comment by Sean10** [comment]
Sorry for the misleading customStyle. 
Now it only support css selector in `src/common-decorations.js`

Example:

``` css
.markless-rainbow-1 {
    color: #000000;
}

.markless-rainbow-2 {
    color: #000000;
}
```
