### ISSUE TITLE
Disable text color?

### ISSUE THREAD

**Issue by Goooyi** [Sean10/markless#40]
Hi, how can I disable of the color rendering of body text? I want to disable all color except for code blocks

**Comment by Sean10** [comment]
Maybe like  this?

``` css
.markless-rainbow-1 {
    color: #000000;
}

.markless-rainbow-2 {
    color: #000000;
}
```
